export {
  CancelParcelDocument as CANCEL_PARCEL,
  GetParcelImportDocument as GET_PARCEL_IMPORT,
  GetParcelImportsDocument as GET_PARCEL_IMPORTS,
  GetParcelDocument as PARCEL,
  GetParcelByTrackingNumberDocument as PARCEL_BY_TRACKING_NUMBER,
  GetInboundReceivingSessionDocument as GET_INBOUND_RECEIVING_SESSION,
  GetOpenInboundManifestsDocument as GET_OPEN_INBOUND_MANIFESTS,
  GetParcelTrackingEventsDocument as GET_PARCEL_TRACKING_EVENTS,
  GetPreLoadParcelsDocument as PRELOAD_PARCELS,
  GetPreLoadParcelsConnectionDocument as PRELOAD_PARCELS_CONNECTION,
  GetParcelsForRouteCreationDocument as PARCELS_FOR_ROUTE,
  RegisterParcelDocument as REGISTER_PARCEL,
  ConfirmInboundReceivingSessionDocument as CONFIRM_INBOUND_RECEIVING_SESSION,
  GetRegisteredParcelsDocument as REGISTERED_PARCELS,
  ScanInboundParcelDocument as SCAN_INBOUND_PARCEL,
  StartInboundReceivingSessionDocument as START_INBOUND_RECEIVING_SESSION,
  TransitionParcelStatusDocument as TRANSITION_PARCEL_STATUS,
  UpdateParcelDocument as UPDATE_PARCEL,
} from "./generated";
export type {
  CancelParcelMutation,
  CancelParcelMutationVariables,
  GetParcelImportQuery,
  GetParcelImportQueryVariables,
  GetParcelImportsQuery,
  GetParcelImportsQueryVariables,
  GetInboundReceivingSessionQuery,
  GetInboundReceivingSessionQueryVariables,
  GetOpenInboundManifestsQuery,
  GetOpenInboundManifestsQueryVariables,
  GetParcelByTrackingNumberQuery,
  GetParcelByTrackingNumberQueryVariables,
  GetParcelQuery,
  GetParcelQueryVariables,
  GetParcelTrackingEventsQuery,
  GetParcelTrackingEventsQueryVariables,
  GetPreLoadParcelsQuery,
  GetPreLoadParcelsConnectionQuery,
  GetPreLoadParcelsConnectionQueryVariables,
  GetPreLoadParcelsQueryVariables,
  GetParcelsForRouteCreationQuery,
  GetParcelsForRouteCreationQueryVariables,
  GetRegisteredParcelsQuery,
  GetRegisteredParcelsQueryVariables,
  ParcelFilterInput,
  ParcelSortInput,
  RegisterParcelMutation,
  RegisterParcelMutationVariables,
  ConfirmInboundReceivingSessionMutation,
  ConfirmInboundReceivingSessionMutationVariables,
  ScanInboundParcelMutation,
  ScanInboundParcelMutationVariables,
  StartInboundReceivingSessionMutation,
  StartInboundReceivingSessionMutationVariables,
  TransitionParcelStatusMutation,
  TransitionParcelStatusMutationVariables,
  UpdateParcelMutation,
  UpdateParcelMutationVariables,
} from "./generated";
